name: Build & Release

on:
  push:
    tags:
      - v.*
  workflow_dispatch:

env:
  pkgname: ouou-dictation

jobs:
  build-release:
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust Toolchain
        run: rustup default stable

      - name: Install Build Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y libspeechd-dev

      - name: Build (Release)
        run: cargo build --release --verbose

      - name: Move built binary
        run: |
          mv target/release/ouou_dictation${{ matrix.os == 'windows-latest' && '.exe' || '' }} ${{ env.pkgname }}-${{ matrix.os }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.pkgname }}-${{ matrix.os }}
          path: ${{ env.pkgname }}-${{ matrix.os }}
          if-no-files-found: error

      - name: Upload Release
        if: startsWith(github.ref, 'refs/tags')
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ${{ env.pkgname }}-${{ matrix.os }}
